package com.example.utils

fun getLocalizedString(text: String, language: String): String {
    if (language != "Bengali" && language != "বাংলা") return text
    return when (text) {
        "Login" -> "লগইন"
        "Sign Up" -> "সাইন আপ"
        "Home" -> "হোম"
        "Wallet" -> "ওয়ালেট"
        "Leaderboard" -> "লিডারবোর্ড"
        "Team" -> "দল"
        "Profile" -> "প্রোফাইল"
        "Settings" -> "সেটিংস"
        "Profile Settings" -> "প্রোফাইল সেটিংস"
        "Language & Region" -> "ভাষা এবং অঞ্চল"
        "Help & Support" -> "সহায়তা এবং সমর্থন"
        "Log Out" -> "লগ আউট"
        "Dark Mode" -> "ডার্ক মোড"
        "Notifications" -> "বিজ্ঞপ্তি"
        "Edit Profile" -> "প্রোফাইল সম্পাদনা করুন"
        "Save" -> "সংরক্ষণ করুন"
        "Name" -> "নাম"
        "Password" -> "পাসওয়ার্ড"
        "Language" -> "ভাষা"
        "Region/Country" -> "অঞ্চল/দেশ"
        "English" -> "ইংরেজি"
        "Bengali" -> "বাংলা"
        "Reward Cash App" -> "রিওয়ার্ড ক্যাশ অ্যাপ"
        "Current Balance" -> "বর্তমান ব্যালেন্স"
        "Daily Tasks" -> "দৈনিক কাজ"
        "Watch Video" -> "ভিডিও দেখুন"
        "Ad Challenge" -> "অ্যাড চ্যালেঞ্জ"
        "Math Quiz" -> "গণিত কুইজ"
        "Refer & Earn" -> "রেফার করুন এবং আয় করুন"
        "Recent Transactions" -> "সাম্প্রতিক লেনদেন"
        "Transactions" -> "লেনদেন"
        "Withdraw" -> "উত্তোলন"
        "Withdraw Funds" -> "ফান্ড উত্তোলন করুন"
        "Admin Dashboard" -> "অ্যাডমিন ড্যাশবোর্ড"
        "Cancel" -> "বাতিল করুন"
        "Apply" -> "প্রয়োগ করুন"
        "Submit" -> "জমা দিন"
        "Privacy Policy" -> "গোপনীয়তা নীতি"
        "Email" -> "ইমেইল"
        "Welcome Back" -> "স্বাগতম"
        "Login to continue earning" -> "উপার্জন চালিয়ে যেতে লগইন করুন"
        "Create Account" -> "অ্যাকাউন্ট তৈরি করুন"
        "Start earning rewards today" -> "আজই পুরষ্কার জেতা শুরু করুন"
        "Please enter email and password" -> "অনুগ্রহ করে ইমেল এবং পাসওয়ার্ড দিন"
        "Please enter name, email and password" -> "অনুগ্রহ করে নাম, ইমেল এবং পাসওয়ার্ড দিন"
        "Don't have an account? Sign Up" -> "অ্যাকাউন্ট নেই? সাইন আপ করুন"
        "Already have an account? Login" -> "ইতিমধ্যে অ্যাকাউন্ট আছে? লগইন করুন"
        "Please fill completely" -> "অনুগ্রহ করে সম্পূর্ণ ফর্মটি পূরণ করুন"
        "You have already applied a referral code." -> "আপনি ইতিমধ্যে একটি রেফারেল কোড প্রয়োগ করেছেন।"
        "Your Referral Code" -> "আপনার রেফারেল কোড"
        "Enter Referral Code" -> "রেফারেল কোড দিন"
        "Share" -> "শেয়ার করুন"
        "Account Actions" -> "অ্যাকাউন্ট অ্যাকশন"
        "App Settings" -> "অ্যাপ সেটিংস"
        "Close" -> "বন্ধ করুন"
        "Done" -> "হয়েছে"
        "Country" -> "অঞ্চল/দেশ"
        "India" -> "ভারত"
        "Bangladesh" -> "বাংলাদেশ"
        "Disabled" -> "নিষ্ক্রিয়"
        "Earn" -> "আয় করুন"
        "Remaining" -> "বাকি আছে"
        "Coins" -> "কয়েন"
        "Correct!" -> "সঠিক!"
        "Close ad to continue" -> "অ্যাড বন্ধ করুন"
        "VERIFIED ACCOUNT" -> "যাচাইকৃত অ্যাকাউন্ট"
        "Please connect VPN" -> "ভিপিএন কানেক্ট করুন"
        "OK" -> "ঠিক আছে"
        "You earned" -> "আপনি আয় করেছেন"
        "Total Users" -> "মোট ব্যবহারকারী"
        "Watch Ad" -> "অ্যাড দেখুন"
        "Refer Friends" -> "বন্ধুদের রেফার করুন"
        "Give" -> "দাও"
        "Get" -> "পাও"
        "Daily Quiz" -> "দৈনিক কুইজ"
        "Wallet Management" -> "ওয়ালেট ব্যবস্থাপনা"
        "View Transactions" -> "লেনদেন দেখুন"
        "Referral Program" -> "রেফারেল প্রোগ্রাম"
        "Request Withdrawal" -> "উত্তোলনের অনুরোধ করুন"
        "Withdrawal Disabled (By Admin)" -> "উত্তোলন নিষ্ক্রিয় (অ্যাডমিন দ্বারা)"
        "How to Work" -> "কিভাবে কাজ করবেন"
        "1. Complete daily tasks like watching videos or math quizzes.\n2. Earn points for each task.\n3. Refer friends to earn bonus points.\n4. Withdraw your points as cash from the wallet." -> "১. ভিডিও দেখা বা কুইজের মতো দৈনিক কাজ সম্পন্ন করুন।\n২. প্রতিটি কাজের জন্য পয়েন্ট আয় করুন।\n৩. বোনাস পয়েন্ট পেতে বন্ধুদের রেফার করুন।\n৪. ওয়ালেট থেকে ক্যাশ হিসেবে পয়েন্ট উত্তোলন করুন।"
        "You have completely watched an advertisement video." -> "আপনি সফলভাবে একটি সম্পূর্ণ ভিডিও অ্যাড দেখেছেন।"
        "Select Method" -> "উত্তোলনের মাধ্যম নির্বাচন করুন"
        "Account Number" -> "অ্যাকাউন্ট নম্বর"
        "Amount in BDT (৳)" -> "পরিমাণ বিডিটি (৳)"
        "Points to Withdraw (Min 100)" -> "পয়েন্ট (সর্বনিম্ন ১০০)"
        "Withdraw Cash" -> "ক্যাশ উত্তোলন"
        "You have reached the limit for today!" -> "আপনি আজকের লিমিট শেষ করেছেন!"
        "Daily Rewards Streak" -> "দৈনিক পুরস্কারের ধারা"
        "Notice: Earn double points today on Daily Quiz! Get instant withdrawals via Bkash/Nagad. Join our Telegram!" -> "নোটিশ: আজকের কুইজে দ্বিগুণ পয়েন্ট পান! বিকাশ ও নগদে পাবেন সুপার ফাস্ট পেমেন্ট। টেলিগ্রামে যোগ দিন!"
        "Claimed today's check-in bonus of" -> "আজকের চেক-ইন বোনাস পেয়েছেন"
        "You have already claimed this today!" -> "আপনি আজ ইতিমধ্যেই এটি ক্লেইম করেছেন!"
        "Come back tomorrow to unlock Day" -> "আগামীকাল আবার আসুন দিন"
        "Top Earners Leaderboard" -> "লিডারবোর্ড - শীর্ষ উপার্জনকারী"
        "No data available" -> "কোনো তথ্য উপলব্ধ নেই"
        "Lucky Spin Pool" -> "ভাগ্যবান স্পিন পুল"
        "Scratch & Win" -> "স্ক্র্যাচ এবং জিতুন"
        "Lucky Spin" -> "ভাগ্যবান স্পিন"
        "Scratch Card" -> "স্ক্র্যাচ কার্ড"
        "Day" -> "দিন"
        "Spins" -> "স্পিন"
        "Scratches" -> "স্ক্র্যাচ"
        else -> text
    }
}
